# Use container-based infrastructure for quicker build start-up
sudo: false
language: minimal
env:
  # Path to 'hadolint' binary
  HADOLINT: "${HOME}/hadolint"
before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C80E383C3DE9F082E01391A0366C67DE91CA5D5F
  - sudo apt-get -y install apt-transport-https
  - echo "deb https://packages.cisofy.com/community/lynis/deb/ stable main" | sudo tee /etc/apt/sources.list.d/cisofy-lynis.list
  - sudo apt-get update
  - sudo apt-get -y install lynis
  - wget https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
  - tar xf kubeval-linux-amd64.tar.gz
  - sudo cp kubeval /usr/local/bin
addons:
  apt:
    update: true
install:
  # Download hadolint binary and set it as executable
  - curl -sL -o ${HADOLINT} "https://github.com/hadolint/hadolint/releases/download/v1.17.3/hadolint-$(uname -s)-$(uname -m)"
  - chmod 700 ${HADOLINT}
script:
  - sudo kubeval kubernetes-deployment.yml
  - sudo lynis audit dockerfile Dockerfile --no-colors 
  - ${HADOLINT} --ignore DL3003 --ignore DL3008 Dockerfile
  - docker build . -t varnav/binance-node
  - docker run --rm -d --name binance varnav/binance-node
  - sleep 5
  - docker logs binance | head -n 20
  - sleep 15
  - docker logs --tail 20 binance
  - docker exec -t binance bnbcli version
  - docker stop binance
